device:
  device_type: nokia_sros
  ip: 100.72.4.4
  username:
  password:
  global_delay_factor: 2
  session_log: netmiko_session.log

port: 1/3/4 1/3/5 # Указываем несколько портов через пробел
log_file: monitor_sap_stats.log
direction: both   # ingress, egress или both
service_id: 315704736  # none или если указан конкретный service_id, работает для конкретного сервиса (напр., 318608115)