destination_address: 192.168.233.255
destination_port: '9999'
packet_size: '256'
protocol: UDP
qos:
  dscp: ''
  ecn: ''
  ip_precedence: ''
source_address: 192.168.233.1
source_port: '12345'
speed_mode: pps
speed_value: '1000'
threads: '4'
traffic_type: broadcast
